<?php
namespace Database\Seeders;

use App\Models\Client;
use Illuminate\Database\Seeder;

class ClientSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Client::create([
            'name' => 'Par Servicios',
            'phone' => '300 000 00 00',
            'email' => 'parservicios@correo.com',
            'acronym' => 'PAR',
            'contact_person' => 'Par Sercvicios',
            'created_users_id' => 1,
            'mp_clients_id'    => 3,
        ]);


        Client::insert([
            [
                'name'             => 'AFC',
                'phone'            => '300',
                'email'            => 'afc@correo.com',
                'acronym'          => 'AFC',
                'contact_person'   => 'AFC',
                'created_users_id' => 1,
                'mp_clients_id'    => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'ALCANOS',
                'phone'            => '300',
                'email'            => 'alc@correo.com',
                'acronym'          => 'ALC',
                'contact_person'   => 'ALC',
                'created_users_id' => 1,
                'mp_clients_id'    => 167,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'ALSERTEC SAS',
                'phone'            => '300',
                'email'            => 'als@correo.com',
                'acronym'          => 'ALS',
                'contact_person'   => 'ALS',
                'created_users_id' => 1,
                'mp_clients_id'    => 155,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'CALIDDA',
                'phone'            => '300',
                'email'            => 'cal@correo.com',
                'acronym'          => 'CAL',
                'contact_person'   => 'CAL',
                'created_users_id' => 1,
                'mp_clients_id'    => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'CANACOL',
                'phone'            => '300',
                'email'            => 'can@correo.com',
                'acronym'          => 'CAN',
                'contact_person'   => 'CAN',
                'created_users_id' => 1,
                'mp_clients_id'    => 68,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'CEDCO',
                'phone'            => '300',
                'email'            => 'ced@correo.com',
                'acronym'          => 'CED',
                'contact_person'   => 'CED',
                'created_users_id' => 1,
                'mp_clients_id'    => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'CENIT',
                'phone'            => '300',
                'email'            => 'cen@correo.com',
                'acronym'          => 'CEN',
                'contact_person'   => 'CEN',
                'created_users_id' => 1,
                'mp_clients_id'    => 46,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'CEPSA',
                'phone'            => '300',
                'email'            => 'cep@correo.com',
                'acronym'          => 'CEP',
                'contact_person'   => 'CEP',
                'created_users_id' => 1,
                'mp_clients_id'    => 9,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'CERREJON',
                'phone'            => '300',
                'email'            => 'cer@correo.com',
                'acronym'          => 'CER',
                'contact_person'   => 'CER',
                'created_users_id' => 1,
                'mp_clients_id'    => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'CLUB DE REGATAS',
                'phone'            => '300',
                'email'            => 'clu@correo.com',
                'acronym'          => 'CLU',
                'contact_person'   => 'CLU',
                'created_users_id' => 1,
                'mp_clients_id'    => 172,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'COBB',
                'phone'            => '300',
                'email'            => 'cob@correo.com',
                'acronym'          => 'COB',
                'contact_person'   => 'COB',
                'created_users_id' => 1,
                'mp_clients_id'    => 173,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'CONTINENTAL GOLD',
                'phone'            => '300',
                'email'            => 'con@correo.com',
                'acronym'          => 'CON',
                'contact_person'   => 'CON',
                'created_users_id' => 1,
                'mp_clients_id'    => 144,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'CTEEP',
                'phone'            => '300',
                'email'            => 'cte@correo.com',
                'acronym'          => 'CTE',
                'contact_person'   => 'CTE',
                'created_users_id' => 1,
                'mp_clients_id'    => 86,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'EBSA',
                'phone'            => '300',
                'email'            => 'ebs@correo.com',
                'acronym'          => 'EBS',
                'contact_person'   => 'EBS',
                'created_users_id' => 1,
                'mp_clients_id'    => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'EMERALD',
                'phone'            => '300',
                'email'            => 'eme@correo.com',
                'acronym'          => 'EME',
                'contact_person'   => 'EME',
                'created_users_id' => 1,
                'mp_clients_id'    => 19,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'ENLACE',
                'phone'            => '300',
                'email'            => 'enl@correo.com',
                'acronym'          => 'ENL',
                'contact_person'   => 'ENL',
                'created_users_id' => 1,
                'mp_clients_id'    => 110,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'ERM',
                'phone'            => '300',
                'email'            => 'erm@correo.com',
                'acronym'          => 'ERM',
                'contact_person'   => 'ERM',
                'created_users_id' => 1,
                'mp_clients_id'    => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'Estandar',
                'phone'            => '300',
                'email'            => 'est@correo.com',
                'acronym'          => 'EST',
                'contact_person'   => 'EST',
                'created_users_id' => 1,
                'mp_clients_id'    => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'FRONTERA',
                'phone'            => '300',
                'email'            => 'fro@correo.com',
                'acronym'          => 'FRO',
                'contact_person'   => 'FRO',
                'created_users_id' => 1,
                'mp_clients_id'    => 123,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'GECOLSA',
                'phone'            => '300',
                'email'            => 'gec@correo.com',
                'acronym'          => 'GEC',
                'contact_person'   => 'GEC',
                'created_users_id' => 1,
                'mp_clients_id'    => 148,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'GRAN TIERRA',
                'phone'            => '300',
                'email'            => 'gra@correo.com',
                'acronym'          => 'GRA',
                'contact_person'   => 'GRA',
                'created_users_id' => 1,
                'mp_clients_id'    => 17,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'HOCOL',
                'phone'            => '300',
                'email'            => 'hoc@correo.com',
                'acronym'          => 'HOC',
                'contact_person'   => 'HOC',
                'created_users_id' => 1,
                'mp_clients_id'    => 1,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'INTERCHILE',
                'phone'            => '300',
                'email'            => 'ich@correo.com',
                'acronym'          => 'ICH',
                'contact_person'   => 'ICH',
                'created_users_id' => 1,
                'mp_clients_id'    => 141,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'INTERCOLOMBIA',
                'phone'            => '300',
                'email'            => 'ico@correo.com',
                'acronym'          => 'ICO',
                'contact_person'   => 'ICO',
                'created_users_id' => 1,
                'mp_clients_id'    => 66,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'LEWIS',
                'phone'            => '300',
                'email'            => 'lew@correo.com',
                'acronym'          => 'LEW',
                'contact_person'   => 'LEW',
                'created_users_id' => 1,
                'mp_clients_id'    => 24,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'MIDSTREAM',
                'phone'            => '300',
                'email'            => 'mid@correo.com',
                'acronym'          => 'MID',
                'contact_person'   => 'MID',
                'created_users_id' => 1,
                'mp_clients_id'    => 75,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'MisCatalogos',
                'phone'            => '300',
                'email'            => 'mca@correo.com',
                'acronym'          => 'MCA',
                'contact_person'   => 'MCA',
                'created_users_id' => 1,
                'mp_clients_id'    => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'NEW GRANADA',
                'phone'            => '300',
                'email'            => 'new@correo.com',
                'acronym'          => 'NEW',
                'contact_person'   => 'NEW',
                'created_users_id' => 1,
                'mp_clients_id'    => 31,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'ODC',
                'phone'            => '300',
                'email'            => 'odc@correo.com',
                'acronym'          => 'ODC',
                'contact_person'   => 'ODC',
                'created_users_id' => 1,
                'mp_clients_id'    => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'PBI',
                'phone'            => '300',
                'email'            => 'pbi@correo.com',
                'acronym'          => 'PBI',
                'contact_person'   => 'PBI',
                'created_users_id' => 1,
                'mp_clients_id'    => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'PDI',
                'phone'            => '300',
                'email'            => 'pdi@correo.com',
                'acronym'          => 'PDI',
                'contact_person'   => 'PDI',
                'created_users_id' => 1,
                'mp_clients_id'    => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'PERENCO',
                'phone'            => '300',
                'email'            => 'per@correo.com',
                'acronym'          => 'PER',
                'contact_person'   => 'PER',
                'created_users_id' => 1,
                'mp_clients_id'    => 51,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'PETROBRAS',
                'phone'            => '300',
                'email'            => 'pbr@correo.com',
                'acronym'          => 'PBR',
                'contact_person'   => 'PBR',
                'created_users_id' => 1,
                'mp_clients_id'    => 15,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'PETROMIL',
                'phone'            => '300',
                'email'            => 'pmi@correo.com',
                'acronym'          => 'PMI',
                'contact_person'   => 'PMI',
                'created_users_id' => 1,
                'mp_clients_id'    => 130,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'PETROSUD',
                'phone'            => '300',
                'email'            => 'psu@correo.com',
                'acronym'          => 'PSU',
                'contact_person'   => 'PSU',
                'created_users_id' => 1,
                'mp_clients_id'    => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'PROMIGAS',
                'phone'            => '300',
                'email'            => 'pro@correo.com',
                'acronym'          => 'PRO',
                'contact_person'   => 'PRO',
                'created_users_id' => 1,
                'mp_clients_id'    => 95,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'RCN',
                'phone'            => '300',
                'email'            => 'rcn@correo.com',
                'acronym'          => 'RCN',
                'contact_person'   => 'RCN',
                'created_users_id' => 1,
                'mp_clients_id'    => 169,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'REP PERU',
                'phone'            => '300',
                'email'            => 'rep@correo.com',
                'acronym'          => 'REP',
                'contact_person'   => 'REP',
                'created_users_id' => 1,
                'mp_clients_id'    => 85,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'SOE',
                'phone'            => '300',
                'email'            => 'soe@correo.com',
                'acronym'          => 'SOE',
                'contact_person'   => 'SOE',
                'created_users_id' => 1,
                'mp_clients_id'    => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'TECPETROL',
                'phone'            => '300',
                'email'            => 'tec@correo.com',
                'acronym'          => 'TEC',
                'contact_person'   => 'TEC',
                'created_users_id' => 1,
                'mp_clients_id'    => 72,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'TGI',
                'phone'            => '300',
                'email'            => 'tgi@correo.com',
                'acronym'          => 'TGI',
                'contact_person'   => 'TGI',
                'created_users_id' => 1,
                'mp_clients_id'    => null,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'VANTI',
                'phone'            => '300',
                'email'            => 'van@correo.com',
                'acronym'          => 'VAN',
                'contact_person'   => 'VAN',
                'created_users_id' => 1,
                'mp_clients_id'    => 131,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'CONTUGAS',
                'phone'            => '300',
                'email'            => 'ctg@correo.com',
                'acronym'          => 'CTG',
                'contact_person'   => 'CTG',
                'created_users_id' => 1,
                'mp_clients_id'    => 82,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'ELECTRODUNAS',
                'phone'            => '300',
                'email'            => 'ele@correo.com',
                'acronym'          => 'ELE',
                'contact_person'   => 'ELE',
                'created_users_id' => 1,
                'mp_clients_id'    => 170,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'TRANSELCA',
                'phone'            => '300',
                'email'            => 'tra@correo.com',
                'acronym'          => 'TRA',
                'contact_person'   => 'TRA',
                'created_users_id' => 1,
                'mp_clients_id'    => 79,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'HYDRAULIC',
                'phone'            => '300',
                'email'            => 'hyd@correo.com',
                'acronym'          => 'HYD',
                'contact_person'   => 'HYD',
                'created_users_id' => 1,
                'mp_clients_id'    => 151,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'RELIANZ',
                'phone'            => '300',
                'email'            => 'rel@correo.com',
                'acronym'          => 'REL',
                'contact_person'   => 'REL',
                'created_users_id' => 1,
                'mp_clients_id'    => 143,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'name'             => 'COSTERA',
                'phone'            => '300',
                'email'            => 'cos@correo.com',
                'acronym'          => 'COS',
                'contact_person'   => 'COS',
                'created_users_id' => 1,
                'mp_clients_id'    => 174,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
        ]);

        // Client::factory(100)->create();
    }
}
