<?php

namespace Database\Seeders;

use App\Models\ClientDocument;
use Illuminate\Database\Seeder;

class ClientDocumentSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        truncate('client_documents');

        $type = ['OB','OB','OP'];

        for ($i=1; $i <= 49 ; $i++) {

            ClientDocument::insert([
            # Liviano / Nacional
                [
                    'clients_id'       => $i,
                    'documents_id'     => 1,
                    'register_type'    => 'L',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 5,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 2,
                    'register_type'    => 'L',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => 'Expedición no mayor a 3 meses',
                    'commentary'       => null,
                    'stage_tasks_id'   => 5,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 3,
                    'register_type'    => 'L',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 5,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 4,
                    'register_type'    => 'L',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 5,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 5,
                    'register_type'    => 'L',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 6,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 6,
                    'register_type'    => 'L',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 6,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 7,
                    'register_type'    => 'L',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 6,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 8,
                    'register_type'    => 'L',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 6,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 9,
                    'register_type'    => 'L',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 7,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 10,
                    'register_type'    => 'L',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 7,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 11,
                    'register_type'    => 'L',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 7,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 12,
                    'register_type'    => 'L',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 7,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 13,
                    'register_type'    => 'L',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 7,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 14,
                    'register_type'    => 'L',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 8,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 15,
                    'register_type'    => 'L',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 8,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 16,
                    'register_type'    => 'L',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 8,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 17,
                    'register_type'    => 'L',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 8,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
            ///////////////////////////////////

            #Integral / Nacional
                [
                    'clients_id'       => $i,
                    'documents_id'     => 1,
                    'register_type'    => 'I',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => 'Expedición no mayor a 3 meses',
                    'commentary'       => null,
                    'stage_tasks_id'   => 5,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 2,
                    'register_type'    => 'I',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 5,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 3,
                    'register_type'    => 'I',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 5,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 4,
                    'register_type'    => 'I',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 5,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 5,
                    'register_type'    => 'I',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 6,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 6,
                    'register_type'    => 'I',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 6,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 7,
                    'register_type'    => 'I',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 6,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 8,
                    'register_type'    => 'I',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 6,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 9,
                    'register_type'    => 'I',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 7,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 10,
                    'register_type'    => 'I',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 7,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 11,
                    'register_type'    => 'I',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 7,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 12,
                    'register_type'    => 'I',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 7,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 13,
                    'register_type'    => 'I',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 7,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 14,
                    'register_type'    => 'I',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 8,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 15,
                    'register_type'    => 'I',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 8,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 16,
                    'register_type'    => 'I',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 8,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 17,
                    'register_type'    => 'I',
                    'provider_type'    => 'N',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 8,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
            ///////////////////////////////////

            # Liviano / Internacional
                [
                    'clients_id'       => $i,
                    'documents_id'     => 1,
                    'register_type'    => 'L',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => 'Expedición no mayor a 3 meses',
                    'commentary'       => null,
                    'stage_tasks_id'   => 5,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 2,
                    'register_type'    => 'L',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 5,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 3,
                    'register_type'    => 'L',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 5,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 4,
                    'register_type'    => 'L',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 5,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 5,
                    'register_type'    => 'L',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 6,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 6,
                    'register_type'    => 'L',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 6,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 7,
                    'register_type'    => 'L',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 6,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 8,
                    'register_type'    => 'L',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 6,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 9,
                    'register_type'    => 'L',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 7,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 10,
                    'register_type'    => 'L',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 7,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 11,
                    'register_type'    => 'L',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 7,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 12,
                    'register_type'    => 'L',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 7,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 13,
                    'register_type'    => 'L',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 7,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 14,
                    'register_type'    => 'L',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 8,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 15,
                    'register_type'    => 'L',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 8,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 16,
                    'register_type'    => 'L',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 8,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 17,
                    'register_type'    => 'L',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 8,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
            ///////////////////////////////////

            # Integral / Internacional
                [
                    'clients_id'       => $i,
                    'documents_id'     => 1,
                    'register_type'    => 'I',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => 'Expedición no mayor a 3 meses',
                    'commentary'       => null,
                    'stage_tasks_id'   => 5,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 2,
                    'register_type'    => 'I',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 5,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 3,
                    'register_type'    => 'I',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 5,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 4,
                    'register_type'    => 'I',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 5,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 5,
                    'register_type'    => 'I',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 6,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 6,
                    'register_type'    => 'I',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 6,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 7,
                    'register_type'    => 'I',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 6,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 8,
                    'register_type'    => 'I',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 6,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 9,
                    'register_type'    => 'I',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 7,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 10,
                    'register_type'    => 'I',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 7,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 11,
                    'register_type'    => 'I',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 7,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 12,
                    'register_type'    => 'I',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 7,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 13,
                    'register_type'    => 'I',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 7,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 14,
                    'register_type'    => 'I',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 8,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 15,
                    'register_type'    => 'I',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 8,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 16,
                    'register_type'    => 'I',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 8,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'clients_id'       => $i,
                    'documents_id'     => 17,
                    'register_type'    => 'I',
                    'provider_type'    => 'I',
                    'document_type'    => $type[array_rand($type)],
                    'validity'         => null,
                    'commentary'       => null,
                    'stage_tasks_id'   => 8,
                    'created_users_id' => 1,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
            ]);
        }
    }
}
